# Generated by Django 2.2.5 on 2020-02-07 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=200)),
                ('sub_title', models.CharField(blank=True, max_length=200)),
                ('about_photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('about_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.Realtor'),
        ),
    ]
